SELECT sysdate from dual;

SELECT  SYSDATE-1 어제,
SYSDATE 오늘,
SYSDATE+1 내일
FROM DUAL;

SELECT ROUND(SYSDATE-HIREDATE)근무일수
FROM employee;

SELECT HIREDATE,
TRUNC(HIREDATE,'MONTH')
FROM EMPLOYEE;

SELECT ENAME,SYSDATE,HIREDATE,
TRUNC (MONTHS_BETWEEN(SYSDATE,HIREDATE))
FROM EMPLOYEE;

SELECT ENAME,HIREDATE,
ADD_MONTHS(HIREDATE,6)
FROM EMPLOYEE;


SELECT SYSDATE,
NEXT_DAY(SYSDATE,'토요일')FROM DUAL;

SELECT ENAME,HIREDATE,
LAST_DAY(HIREDATE)
FROM EMPLOYEE;

SELECT LAST_DAY(sysdate) FROM dual;

select sysdate,
next_day(sysdate,'토요일')
from dual;
