 SELECT * FROM employee;
 ;
 department d;
 
 SELECT * FROM EMPLOYEE E1, EMPLOYEE E2;
 
 SELECT * FROM EMPLOYEE WHERE ENO = 7369;
 SELECT * FROM EMPLOYEE WHERE ENO = 7902;
 
 SELECT * FROM EMPLOYEE E, DEPARTMENT D
 WHERE E.DNO = D.DENO;
 
 
 SELECT EMPLOYEES.ENAME AS "사원이름", MANAGER.ENAME AS "직속상관이름"
 FROM EMPLOYEE EMPLOYEES, EMPLOYEE MANAGER
 WHERE EMPLOYEES.MANAGER = MANAGER.ENO;
 
 SELECT EMPLOYEES.ENAME || '의 직속 상관은' || MANAGER.ENAME
 FROM EMPLOYEE EMPLOYEES JOIN EMPLOYEE MANAGER
 ON EMPLOYEES.MANAGER=MANAGER.ENO;