 SELECT * FROM EMPLOYEE, DEPARTMENT --EQUI JOIN
 WHERE EMPLOYEE.DNO = DEPARTMENT.DNO;
 
 
 SELECT ENO, ENAME, DNAME
 FROM EMPLOYEE, DEPARTMENT
 WHERE EMPLOYEE.DNO = DEPARTMENT.DNO -- EQUI JOIN 후 AND연산자 
 AND ENO=7788;
 
 SELECT ENO, ENAME, DNAME, DNO --DNO로 인한 실행오류
 FROM EMPLOYEE, DEPARTMENT
 WHERE EMPLOYEE.DNO = DEPARTMENT.DNO
 AND ENO= 7788;
 
 SELECT EMPLOYEE.ENO, EMPLOYEE.ENAME, DEPARTMENT.DNAME, EMPLOYEE.DNO--칼럼명앞에 테이블명 명시 
 FROM EMPLOYEE, DEPARTMENT
 WHERE EMPLOYEE.DNO = DEPARTMENT.DNO
 AND EMPLOYEE.ENO=7788;
 
 SELECT ENO, ENAME, DNAME, EMPLOYEE.DNO--중복되지 않은 칼럼명이면 굳이 사용안해도됨.
 FROM EMPLOYEE, DEPARTMENT
 WHERE EMPLOYEE.DNO = DEPARTMENT.DNO
 AND ENO = 7788;
 
 SELECT E.ENO, E.ENAME, D.DNAME, E.DNO--테이블별칭
 FROM EMPLOYEE E, DEPARTMENT D
 WHERE E.DNO = D.DNO
 AND E.ENO=7788;
 
 SELECT E.ENO, E.ENAME, D.DNAME, DNO --NATURAL 조인 시에는 중복칼럼에 별칭 쓰지않아야함
 FROM EMPLOYEE E NATURAL JOIN DEPARTMENT D
 WHERE E.ENO=7788;
 
 SELECT E.ENO , E.ENAME, D.DNAME, DNO
 FROM EMPLOYEE E JOIN DEPARTMENT D
 USING(DNO)
 WHERE E.ENO=7788;
 
 
 
 
 
 
 